/// Flutter icons CodeIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CodeIcon
///      fonts:
///       - asset: fonts/CodeIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CodeIcon {
  CodeIcon._();

  static const _kFontFam = 'CodeIcon';

  static const IconData placeholder_1 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData slideshow_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData suitcase_1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData tag_1 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ticket_1 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData certificate_1 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData clipboard_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData coins__1__1 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData contact_1_ = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData contact = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData creativity_1 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData credit_card_1 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData crown_1 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData dashboard_1 = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData discount_1 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData house_1 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData house = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData invoice_1 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData money_1 = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData money_2 = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData certificate_2 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData leaf_1 = const IconData(0xe816, fontFamily: _kFontFam);
}
